CREATE TABLE estado (
    id BIGINT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(80) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=INNODB CHARSET=UTF8MB4;

INSERT INTO ESTADO (NOME)
SELECT DISTINCT NOME_ESTADO
FROM CIDADE;

ALTER TABLE CIDADE
ADD COLUMN estado_id BIGINT NOT NULL;

-- UPDATE CIDADE C
-- SET C.ESTADO_ID
-- = (SELECT E.ID FROM ESTADO E WHERE E.NOME = C.NOME_ESTADO);

UPDATE CIDADE C
INNER JOIN ESTADO E
ON E.NOME = C.NOME_ESTADO
SET C.ESTADO_ID = E.ID;

ALTER TABLE CIDADE
ADD CONSTRAINT fk_cidade_estado
FOREIGN KEY (estado_id)
REFERENCES estado(id) ;

ALTER TABLE CIDADE
DROP COLUMN NOME_ESTADO;

ALTER TABLE CIDADE CHANGE NOME_CIDADE
nome VARCHAR (80) NOT NULL;